services:
  web:
    image: streamlit-front-end:latest
    depends_on:
      - ollama
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

volumes:
  ollama:
